[%
    T = {
        title="Koha: Change Rules Within Period: Configuration",
        saved_settings="Settings saved",
        saved_circrules="Saved CircRules",
        within_saved_alert="We are currently within a previously defined period! See saved data below",
        to_circrules="Show circulation rules",
        rule_id="Rule id",
        branchcode="Branchcode",
        categorycode="Category code",
        itype="Item type",
        rulename="Rule name",
        rulevalue="Rule value",
        start_date="From date",
        end_date="To date",
        rule_new_value="New value",
        ignore_zero="Ignore zero",
        advanced_settings="Advanced settings",
        save_config="Save configuration",
        alert_warning="The circulation rules might be overwritten by the ChangeRulesPlugin, check the configuration",
        alert_danger="The default circulation rules are currently overwritten by the ChangeRulesPlugin.<br>to check the saved values, head to the plugin configuration",
        configure_link="Check the plugin configuration",
    }
%]