[%
    T = {
        title="Koha : Modifier les règles pendant la période : Configuration",
        saved_settings="Paramètres enregistrés",
        saved_circrules="Règles de circulation enregistrées",
        within_saved_alert="Nous sommes actuellement dans une période préalablement définie ! Voir les données enregistrées ci-dessous",
	to_circrules="Afficher les règles de circulation",
        rule_id="ID de la règle",
        branchcode="Code de la succursale",
        categorycode="Code de la catégorie",
        itype="Type d'élément",
        rulename="Nom de la règle",
        rulevalue="Valeur de la règle",
        start_date="Date de début",
        end_date="Date de fin",
        rule_new_value="Nouvelle valeur",
        ignore_zero="Ignorer zéro",
        advanced_settings="Paramètres avancés",
        save_config="Enregistrer la configuration",
	alert_warning="Les règles de circulation peuvent être remplacées par le plugin ChangeRulesPlugin, vérifiez la configuration",
        alert_danger="Les règles de circulation par défaut sont actuellement remplacées par le plugin ChangeRulesPlugin.<br>Pour vérifier les valeurs enregistrées, rendez-vous dans la configuration du plugin",
        configure_link="Vérifier la configuration du plugin",
    }
%]