[%
    T = {
        title="Koha: Ändra regler inom period: Konfiguration",
        saved_settings="Inställningar sparade",
        saved_circrules="Sparade cirkulationsregler",
        within_saved_alert="Vi befinner oss för närvarande inom en tidigare definierad period! Se sparade data nedan",
        to_circrules="Visa cirkulationsregler",
        rule_id="Regel-id",
        branchcode="Filialkod",
        categorycode="Kategorikod",
        itype="Objekttyp",
        rulename="Regelnamn",
        rulevalue="Regelvärde",
        start_date="Från datum",
        end_date="Till datum",
        rule_new_value="Nytt värde",
        ignore_zero="Ignorera noll",
        advanced_settings="Avancerade inställningar",
        save_config="Spara konfiguration",
        alert_warning="Cirkulationsreglerna kan skrivas över av ChangeRulesPlugin, kontrollera konfigurationen",
        alert_danger="Standardcirkulationsreglerna skrivs för närvarande över av ChangeRulesPlugin.<br>För att kontrollera de sparade värdena, gå till plugin-konfigurationen",
        configure_link="Kontrollera plugin-konfigurationen",
    }
%]